### ISSUE TITLE
[CRASH] Cannot read field "mipmapLevel" because "this.atlas" is null

### ISSUE THREAD

**Issue by asamufaja** [CreeperHost/PolyLib#43]
The crash report points the finger at PolyLib, and I guess it's a conflict with Optifine. It crashes the game right before forge finishes loading all the mods. My other installed mods are in the log.
https://pastebin.com/aVycQwD9

**Comment by brandon3055** [comment]
Can you confirm that this crash only occurs with optifine installed?

**Comment by asamufaja** [comment]
Yeah, here's the crash log for that. https://pastebin.com/225WJY4A
Also this works with oculus so I'll just use that instead of optifine haha.

**Comment by brandon3055** [comment]
I do not see any obvious cause for this crash on our end. 
My best guess is Optifine is doing something that is incompatible with our custom texture loading.
But as Optifine is a closed source mod, troubleshooting that is extremely difficult. 
We would recommend reporting this crash to optifine if you have not done so already.
