### ISSUE TITLE
my game crash with new iris mod

### ISSUE THREAD

**Issue by mojgang0** [CreeperHost/PolyLib#63]
hi my game crash with your mod combin with iris 1.7.1+
can you fix it
its only your mod i test it

**Comment by Cloudhunter** [comment]
Logs

**Comment by mojgang0** [comment]
[latest.log](https://github.com/user-attachments/files/16201258/latest.log)
here

**Comment by mojgang0** [comment]
> Logs

[Uploading latest.log…]()
here

**Comment by gigabit101** [comment]
It looks like you failed at uploading the logs, Try clicking on then link you provided
