### ISSUE TITLE
Polylib required clientside 1.21?

### ISSUE THREAD

**Issue by Karanstr** [CreeperHost/PolyLib#64]
I'm running a vanilla compatible fabric server with polylib installed. Joining on a vanilla client works fine and joining on a forge client works fine. Joining on a fabric client (without polylib installed on the client) causes the following error:
![image_2024-07-14_115353836](https://github.com/user-attachments/assets/47b302c9-86d4-4622-bcfd-4b50b55406f9)

The server is running Fabric 0.15.11, here's the full modlist (with FTBBackups2 being the only mod with polylib as a requisite):
![image_2024-07-14_114702256](https://github.com/user-attachments/assets/6de4efc0-3a65-4a22-9f13-d6a88aea12c4)

This issue only appeared after updating the server to 1.21, running the same mods on 1.20.4 didn't have this issue.

**Comment by gigabit101** [comment]
Fixed in latest build
