### ISSUE TITLE
[1.21] Polylib crashed game on start up

### ISSUE THREAD

**Issue by Periam** [CreeperHost/PolyLib#66]
After installing polylib with the below list of mods the game crashed

MC 1.21
Neoforge 21.0.148
Polylib-2100.0.3-build.158-neoforge
railcraft-reborn-1.21-1.2.0
jei-1.21-neoforge-19.5.3.67
architectury-13.0.6-neoforge

Screenshot 2024-08-02 161153

[crash-2024-08-02_16.16.44-fml.txt](https://github.com/user-attachments/files/16474406/crash-2024-08-02_16.16.44-fml.txt)
[latest.log](https://github.com/user-attachments/files/16474407/latest.log)

**Comment by gigabit101** [comment]
PolyLib 0.3.159 has been uploaded to CurseForge to resolve this issue, You should see it in a few minutes

**Comment by gigabit101** [comment]
This is now live and should resolve the issue
