### ISSUE TITLE
for some reason this mod is making my mod pack messed up can you fix it or can you help me fix it?

### ISSUE THREAD

**Issue by TheAlienCreator** [CreeperHost/PolyLib#70]
![image_2024-10-03_115914243](https://github.com/user-attachments/assets/5d12c89a-47d2-4868-8df6-10572fad94d0)

hello im trying to make a modpack for minecraft and every time i add this mod its keeps doing the same thing 

mod for 1.20.1

if you wanna speak to me on discord about this here my discord name thea1iencreator

**Comment by gigabit101** [comment]
Pretty sure this is nothing to do with us but can you provide us with the logs?

**Comment by TheAlienCreator** [comment]
it is every time your mod is in my modpack it does this every time i remove this mod this happens

and there no logs because every time i start the pack it crashes aftar 30s at this screen

**Comment by gigabit101** [comment]
Works fine for me and unless I get more info like the logs or what Modpack you are using there is nothing I can do

**Comment by TheAlienCreator** [comment]
ok nvm then i will not use your mod then
